/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Offer {
  'id' : bigint,
  'title' : string,
  'featured' : boolean,
  'active' : boolean,
  'description' : string,
  'affiliateUrl' : string,
  'imageUrl' : string,
  'category' : string,
  'commissionRate' : number,
}
export interface OfferStats {
  'offer' : Offer,
  'clickCount' : bigint,
  'totalEarnings' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOffer' : ActorMethod<
    [string, string, string, string, string, number, boolean, boolean],
    undefined
  >,
  'deleteOffer' : ActorMethod<[bigint], undefined>,
  'getAllOfferStats' : ActorMethod<[], Array<OfferStats>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClickCount' : ActorMethod<[bigint], bigint>,
  'getOfferById' : ActorMethod<[bigint], [] | [Offer]>,
  'getOfferStats' : ActorMethod<[bigint], OfferStats>,
  'getTotalClicks' : ActorMethod<[], bigint>,
  'getTotalEarnings' : ActorMethod<[], number>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listActiveOffers' : ActorMethod<[], Array<Offer>>,
  'logEarning' : ActorMethod<[bigint, number, string, string], undefined>,
  'recordClick' : ActorMethod<[bigint], undefined>,
  'updateOffer' : ActorMethod<
    [bigint, string, string, string, string, string, number, boolean, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];