/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Offer = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'active' : IDL.Bool,
  'description' : IDL.Text,
  'affiliateUrl' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'commissionRate' : IDL.Float64,
});
export const OfferStats = IDL.Record({
  'offer' : Offer,
  'clickCount' : IDL.Nat,
  'totalEarnings' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOffer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'deleteOffer' : IDL.Func([IDL.Nat], [], []),
  'getAllOfferStats' : IDL.Func([], [IDL.Vec(OfferStats)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClickCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getOfferById' : IDL.Func([IDL.Nat], [IDL.Opt(Offer)], ['query']),
  'getOfferStats' : IDL.Func([IDL.Nat], [OfferStats], ['query']),
  'getTotalClicks' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalEarnings' : IDL.Func([], [IDL.Float64], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'logEarning' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Text, IDL.Text], [], []),
  'recordClick' : IDL.Func([IDL.Nat], [], []),
  'updateOffer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Offer = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'active' : IDL.Bool,
    'description' : IDL.Text,
    'affiliateUrl' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'commissionRate' : IDL.Float64,
  });
  const OfferStats = IDL.Record({
    'offer' : Offer,
    'clickCount' : IDL.Nat,
    'totalEarnings' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOffer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'deleteOffer' : IDL.Func([IDL.Nat], [], []),
    'getAllOfferStats' : IDL.Func([], [IDL.Vec(OfferStats)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClickCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getOfferById' : IDL.Func([IDL.Nat], [IDL.Opt(Offer)], ['query']),
    'getOfferStats' : IDL.Func([IDL.Nat], [OfferStats], ['query']),
    'getTotalClicks' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalEarnings' : IDL.Func([], [IDL.Float64], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'logEarning' : IDL.Func([IDL.Nat, IDL.Float64, IDL.Text, IDL.Text], [], []),
    'recordClick' : IDL.Func([IDL.Nat], [], []),
    'updateOffer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };